
@endpoint = https://h6g0sqea41.execute-api.ca-central-1.amazonaws.com/prod/


POST {{endpoint}}/spaces/
Content-Type: application/json
{
    "location": "Montreal",
    "name": "mMonut royal park"
}
###

GET {{endpoint}}/spaces?location=Toronto
